Use ocamlopt instead of ocamlc
Because, running ocaml bytecode programs need CAML_LD_LIBRARY_PATH set
properly. Otherwise you'll see

Fatal error: cannot load shared library dllcamlstrbyt
Reason: dlopen(dllcamlstrbyt.so, 0x000A): tried: 'dllcamlstrbyt.so' (no such file), '/System/Volumes/Preboot/Cryptexes/OSdllcamlstrbyt.so' (no such file), '/usr/lib/dllcamlstrbyt.so' (no such file, not in dyld cache), 'dllcamlstrbyt.so' (no such file)